Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 511, in _read_ready
    self._protocol.data_received(data)
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 285, in data_received
    self.proc._pipe_data_received(self.fd, data)
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 205, in _pipe_data_received
    self._call(self._protocol.pipe_data_received, fd, data)
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 198, in _call
    self._loop.call_soon(cb, *data)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 757, in call_soon
    handle = self._call_soon(callback, args, context)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 773, in _call_soon
    handle = events.Handle(callback, args, self, context)
  File "/usr/lib/python3.10/asyncio/events.py", line 31, in __init__
    def __init__(self, callback, args, loop, context=None):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 59, in build
    rc = await extension.build(
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 110, in build
    if await has_target(args.build_base, 'install'):
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 57, in has_target
    return target in await get_makefile_targets(path)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 77, in get_makefile_targets
    output = await check_output([
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/usr/bin/cmake', '--build', '/mnt/Storage/Documents/MIT/Books/Robotics-2_Lab/Mini_Project/build/conveyorbelt_gazebo', '--target', 'help'] to pass: gmake: *** wait: No child processes.  Stop.
gmake: *** Waiting for unfinished jobs....
gmake: *** wait: No child processes.  Stop.

